### ISSUE TITLE
png function has no quality parameter

### ISSUE THREAD

**Issue by f-heeger** [TheRincon/gc_plotter#6]
I get the following error when running:
> gc.sh genome.fasta 1000 d png

> Error in check.options(new, name.opt = ".X11.Options", envir = .X11env) : 
  c("invalid argument name ‘quality’ in 'png(paste(\"GC Plot.png\"), width = 9 * dpi, height = 7 * dpi, '", "invalid argument name ‘quality’ in '    res = dpi, quality = 100)'")
Calls: png -> check.options

Probably because the png function does not have a "quality" parameter? If I remove the quality option it works. R version is 3.4.4.

**Comment by TheRincon** [comment]
Cheers, I think I fixed it. R version 3.5.2

**Comment by f-heeger** [comment]
Yes it works now.
